#!/bin/bash

date
export PS4=' $SECONDS + '
set -xue

#-----------------------------------------------------------------------
# Source the variable definitions file and the bash utility functions.
#-----------------------------------------------------------------------

. ${GLOBAL_VAR_DEFNS_FP}
. $USHrrfs/source_util_funcs.sh

export USHrrfs=${USHrrfs:-${HOMErrfs}/ush}
export PARMrrfs=${PARMrrfs:-${HOMErrfs}/parm}
export PARMutil=${PARMutil:-${HOMErrfs}/parm/wmo}
export EXECrrfs=${EXECrrfs:-${HOMErrfs}/exec}
export FIXrrfs=${FIXrrfs:-${HOMErrfs}/fix}

export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir $DATA
cd $DATA 

export COMOUT=${COMOUT:-$(compath.py -o $NET/${rrfs_ver})/${RUN}.${PDY}/${cyc}}
export COMIN=${COMIN:-$(compath.py -o $NET/${rrfs_ver})/${RUN}.${PDY}/${cyc}}
export COMOUTwmo=${COMOUTwmo:-${COMOUT}/wmo}

if [ ! -e $COMOUTwmo ]
then
  mkdir -p $COMOUTwmo
fi

. ${GLOBAL_VAR_DEFNS_FP}
. $USHrrfs/source_util_funcs.sh

export cycle="t${cyc}z"
setpdy.sh
. ./PDY
export CDATE=${PDY}${cyc}


${HOMErrfs}/scripts/exrrfs_awips.sh
export err=$?; err_chk

if [ "${KEEPDATA}" != "YES" ]; then
  rm -rf ${DATA}
fi
